version: '3.3'

services:
  db:
    # container_name: bp_db # コンテナ名を指定してください
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./db_data/data:/var/lib/mysql
      - ./db_data/init:/docker-entrypoint-initdb.d

  wordpress:
    # container_name: bp_wp # コンテナ名を指定してください
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - ./www:/var/www/html
      - ./dev:/var/www/html/wp-content/themes/theme-name # テーマ名を指定してください。
      - ./uploads:/var/www/html/wp-content/uploads

  cli:
    # container_name: bp_cli # コンテナ名を指定してください
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    user: xfs
    volumes:
      - ./www:/var/www/html

volumes:
  db_data:
  www:
  dev:
  uploads:
